import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Udaynarayanpur State General Hospital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        <p className={styles.description}>
          Important Notice
          {/* <code className={styles.code}>Updated on 20/09/2022</code> */}
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Vaccination</h2>
            <p>Vaccination is going on. Every Monday to Friday : Covishield. Saturday : Covaxin. 1st Floor 11 a.m to 3 p.m. Booster Dose is also available.</p>
          </div>

          <div className={styles.card}>
            <h2>Rules</h2>
            <p>Keep clean the Hospital area. Do not smoke within the Hospital area. Keep your voice down. Kids below 10 years should not be encouraged for hospital visits.</p>
          </div>

          <div className={styles.card}>
            <h2>Visiting Time</h2>
            <p>Morning 11 a.m to 12 p.m. Evening 4 p.m to 5 p.m</p>
          </div>

          <div className={styles.card}>
            <h2>Emergency</h2>
            <p>
              Emerency ward is in the left of main gate. If it closed emergency service is availabale in Indoor.
            </p>
          </div>
        </div>
      </main>

     
    </div>
  )
}
